# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target '科技头条' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 科技头条
pod 'SDWebImage'

end
